# Generated by Django 4.2 on 2023-06-28 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='experienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Software Developer', max_length=300)),
                ('company', models.CharField(default='Google', max_length=200)),
                ('start', models.DateField(default='2019-04-05', max_length=20)),
                ('end', models.DateField(default=datetime.date.today, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Developed a website', max_length=200)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.experiencedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='softSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='Analytical skills', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('title', models.CharField(default='Software Developer', max_length=100)),
                ('email', models.EmailField(default='johndoe@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+254712345678', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Voting System', max_length=100)),
                ('description', models.CharField(default='Developed and implemented a voting system.', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='Python, PHP, Ruby', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professionalCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Docker form scratch Course (Udemy)', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='educationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='BSc in Mathematics and Computer Science', max_length=250)),
                ('school_name', models.CharField(default='Technical University of Munich', max_length=200)),
                ('start', models.DateField(default='2018-02-04', max_length=20)),
                ('end', models.DateField(default=datetime.date.today, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('title', models.CharField(default='Software Developer', max_length=100)),
                ('image', models.ImageField(blank=True, default='default-profile.jpg', upload_to='photos')),
                ('email', models.EmailField(default='johndoe@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+254712345678', max_length=20)),
                ('website', models.CharField(default='john-doe.com', max_length=100)),
                ('linkedin', models.CharField(default='linkedin.com/in/john-doe', max_length=100)),
                ('github', models.CharField(default='github.com/john-doe', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(default='Certified AWS Developer', max_length=250)),
                ('school_name', models.CharField(default='Amazon Web Services', max_length=200)),
                ('start', models.DateField(default='2018-02-04', max_length=20)),
                ('end', models.DateField(default=datetime.date.today, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='careerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_profile', models.TextField(default='John Doe is a Software developer with a strong passion for using technology to solve problems. He is proficient in Python, PHP programming languages, MYSQL database and Django framework. He is eager to continue learning and growing as a web developer. He enjoys staying up to date with the latest technology trends. He is team player and is excited to contribute his skills and knowledge to any project.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='areaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_interest', models.CharField(default='Reading story books', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
